# Generated by Django 3.2.16 on 2023-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment",
            field=models.ManyToManyField(
                related_name="posts",
                to="blog.Comment",
                verbose_name="Комментарии",
            ),
        ),
    ]
