# Generated by Django 3.2.16 on 2023-07-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_alter_post_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="blog.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="comment",
            field=models.ManyToManyField(
                related_name="comments",
                to="blog.Comment",
                verbose_name="Комментарии",
            ),
        ),
    ]
