# Generated by Django 3.2.16 on 2023-07-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comment",
            field=models.ManyToManyField(
                related_name="posts",
                to="blog.Comment",
                verbose_name="Комментарии",
            ),
        ),
    ]
