# Generated by Django 3.2.16 on 2023-08-04 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_comment_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comment",
        ),
    ]
